### ISSUE TITLE
我想要docker版本

### ISSUE THREAD

**Issue by SoulRui** [Yudaotor/EsportsHelper#1]

**Comment by SoulRui** [comment]
恭喜，我想成为你的第一批测试用户
![189F0DAA](https://user-images.githubusercontent.com/50903413/227708840-0d12800a-db43-4446-81d9-5f313d40ee6c.png)

**Comment by Yudaotor** [comment]
docker不太会打包,抱歉.代码都在,如有需要可以自行研究

**Comment by x2287711259** [comment]
我也想要docker版本，arm机器

**Comment by redr00t** [comment]
I've been trying for days to get it to work on Docker but always with the same problem (I've tried using Alpine and Debian btw).

![imagen](https://github.com/Yudaotor/EsportsHelper/assets/46618211/6e3ec2ea-8fc3-4505-95f3-4b49e712264c)

**Comment by redr00t** [comment]
any idea @Yudaotor

**Comment by redr00t** [comment]
well well...

![imagen](https://github.com/Yudaotor/EsportsHelper/assets/46618211/9f7419d1-c3f1-43db-8a62-7a2a5f8ad22e)

**Comment by Yudaotor** [comment]
> well well...
> 
> ![imagen](https://user-images.githubusercontent.com/46618211/258919573-9f7419d1-c3f1-43db-8a62-7a2a5f8ad22e.png)

is it works?

**Comment by redr00t** [comment]
yes, ready to check & merge

**Comment by x2287711259** [comment]
> yes, ready to check & merge
> 
> My compiled image: https://hub.docker.com/r/redr00t/esportshelper (AMD64 - ARM64 - ARMv7)

How to deploy and set up

**Comment by redr00t** [comment]
> > yes, ready to check & merge
> > My compiled image: https://hub.docker.com/r/redr00t/esportshelper (AMD64 - ARM64 - ARMv7)
> 
> How to deploy and set up

https://github.com/Yudaotor/EsportsHelper/pull/73

**Comment by Yudaotor** [comment]
Finished
