### ISSUE TITLE
Safety measures

### ISSUE THREAD

**Issue by renja-g** [Yudaotor/EsportsHelper#102]
Hello, I know from [EsportsCapsuleFarmer](https://github.com/LeagueOfPoro/EsportsCapsuleFarmer), that at the end people were getting banned, did you do anything to prevent that and if so what did you do?

**Comment by Yudaotor** [comment]
> Hello, I know from [EsportsCapsuleFarmer](https://github.com/LeagueOfPoro/EsportsCapsuleFarmer), that at the end people were getting banned, did you do anything to prevent that and if so what did you do?

I have done security measures. block the small leagu and limit the maximum number of simultaneous watching

**Comment by renja-g** [comment]
And so far there were no problems with such small adjustments?

**Comment by Yudaotor** [comment]
> And so far there were no problems with such small adjustments?

As it stands now, it looks like this

**Comment by renja-g** [comment]
Alright thanks
