### ISSUE TITLE
似乎不能支持多个账号？

### ISSUE THREAD

**Issue by IHutuXian** [Yudaotor/EsportsHelper#11]
将文件分别放入了两个文件夹中，并设置不同的config，但同时打开两个程序时，只有先开启的程序可以运行，第二个程序会提示需要浏览器升级为最新版本。

**Comment by IHutuXian** [comment]
> > 将文件分别放入了两个文件夹中，并设置不同的config，但同时打开两个程序时，只有先开启的程序可以运行，第二个程序会提示需要浏览器升级为最新版本。
> 
> 是的,不支持多个账号

是否会考虑添加支持？如果担心有人借此牟利，或许可以设置账号上限。

**Comment by Yudaotor** [comment]
> 

多开账号这个需求其实不成立,一个人一般只会有一个主号,至于小号就根本没有电竞典藏罐的需要了

**Comment by IHutuXian** [comment]
理解，我尊重作者的想法。
