### ISSUE TITLE
feature request: support ungoogled-chromium for docker version

### ISSUE THREAD

**Issue by zzz6839** [Yudaotor/EsportsHelper#110]
@RedrootDEV 

I believe it's possible to chain ungoogled chromium with EsportsHelper to run this script on headless mode in docker, therefore saving more resources.

https://github.com/ungoogled-software/ungoogled-chromium
https://github.com/ich777/docker-ungoogled-chromium

One of the down side for using google-chromium in docker is the profile path isn't fixed, you have to login first(security alert!), and sometimes google will block the login.
![image](https://github.com/Yudaotor/EsportsHelper/assets/57741549/8aabc12f-49c7-46af-89ce-09c098306c02)
However, with ungoogled-chromium, you have a fixed local profile path(without login of course!).
![image](https://github.com/Yudaotor/EsportsHelper/assets/57741549/3dbc7c6c-2565-4f11-84ab-c3b46e72cc89)
Combine the `userDataDir` and `ChromePath` function from EsportsHelper, in initial setup, run `docker compose run` with config file set to`headless:false`, insert username and password manually and tick "stay signed in". After a successful login, ctrl+C, then turn on headless, save the config file, now `docker compose up -d`, u now have a headless docker version EsportsHelper.

I have verified EsportsHelper works with ungoogled-chromium in windows version.

I hope this idea could help u.

**Comment by RedrootDEV** [comment]
> @RedrootDEV
> 
> I believe it's possible to chain ungoogled chromium with EsportsHelper to run this script on headless mode in docker, therefore saving more resources.
> 
> https://github.com/ungoogled-software/ungoogled-chromium https://github.com/ich777/docker-ungoogled-chromium
> 
> One of the down side for using google-chromium in docker is the profile path isn't fixed, you have to login first(security alert!), and sometimes google will block the login. ![image](https://private-user-images.githubusercontent.com/57741549/302018930-8aabc12f-49c7-46af-89ce-09c098306c02.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyNDI2MTEsIm5iZiI6MTcwNzI0MjMxMSwicGF0aCI6Ii81Nzc0MTU0OS8zMDIwMTg5MzAtOGFhYmMxMmYtNDljNy00NmFmLTg5Y2UtMDljMDk4MzA2YzAyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA2VDE3NTgzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA0OTRlNTVkYzE4ZTMzZDM4NGQ0MjgxNDhhZDVmNDAwZmVjMjJhM2IzZTgyM2I2OWU0MjJkODRlZWE4ZjRmOGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.C9duL-_m6akyzca5In71heUZT3CCB5R0VNJioM80QCM) However, with ungoogled-chromium, you have a fixed local profile path(without login of course!). ![image](https://private-user-images.githubusercontent.com/57741549/302019251-3dbc7c6c-2565-4f11-84ab-c3b46e72cc89.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyNDI2MTEsIm5iZiI6MTcwNzI0MjMxMSwicGF0aCI6Ii81Nzc0MTU0OS8zMDIwMTkyNTEtM2RiYzdjNmMtMjU2NS00ZjExLTg0YWItYzNiNDZlNzJjYzg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA2VDE3NTgzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU4OWNmZmRkMDRhMGY1MDg5YzE5ZGYyM2U4NzM4OTg3MTNlYTdlMmU1NzgwZmU2ZTFiYzQ2MTBmZDFhYjRhZDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wcUOrZE6-eNPbLli5qJ5RmqM-Xp7t7exs3SRAoq79m8) Combine the `userDataDir` and `ChromePath` function from EsportsHelper, in initial setup, run `docker compose run` with config file set to`headless:false`, insert username and password manually and tick "stay signed in". After a successful login, ctrl+C, then turn on headless, save the config file, now `docker compose up -d`, u now have a headless docker version EsportsHelper.
> 
> I have verified EsportsHelper works with ungoogled-chromium in windows version.
> 
> I hope this idea could help u.

I like your idea, I will try to apply it!! The challenge is that the image needs to work for both ARM64 and AMD64 since Ungoogled Chromium binaries are specific to each architecture. I'd rather not have to maintain two versions of the image (one for each architecture).
