### ISSUE TITLE
an issue with stream definition

### ISSUE THREAD

**Issue by NaniDaFuck** [Yudaotor/EsportsHelper#116]
there is a problem with stream quilty when using headless mode 

it writes that quilty changed to 160p but i doesn't i test it more than a time and still consume alot of data after waiting for a while

hope that fixed in next update

**Comment by NaniDaFuck** [comment]
after more test sometimes it stays bugged on 1080p for long time and sometimes it works at 160p idk to be honest what may cause this

hope u check it ^^

**Comment by NaniDaFuck** [comment]
it consumes data like it's 1080p i tested it with netlimiter

**Comment by Yudaotor** [comment]
> it consumes data like it's 1080p i tested it with netlimiter

You can check the browser interface and see if the definition changes automatically.
