### ISSUE TITLE
Giving This Errors

### ISSUE THREAD

**Issue by MehmetCanWT** [Yudaotor/EsportsHelper#118]
![Screenshot_2024-03-22-10-26-14-221_com discord](https://github.com/Yudaotor/EsportsHelper/assets/52177084/4e5a18eb-18a8-49ff-91ed-fd8113611a1b)

watch system work anomaly

**Comment by Yudaotor** [comment]
> ![Screenshot_2024-03-22-10-26-14-221_com discord](https://private-user-images.githubusercontent.com/52177084/315921584-4e5a18eb-18a8-49ff-91ed-fd8113611a1b.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwOTMxMDcsIm5iZiI6MTcxMTA5MjgwNywicGF0aCI6Ii81MjE3NzA4NC8zMTU5MjE1ODQtNGU1YTE4ZWItMThhOC00OWZmLTkxZWQtZmQ4MTEzNjExYTFiLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIyVDA3MzMyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkMTZhNmNiNzFlODM3ODU0ODJlZWNjYjgxNTk2MjcxMDBlYTNmZDhjODdhOGE5YzQ1YWVkOGFmZWI4ZjgzMzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sglcDRI_irrqGvDR8WvJlTWxDodG2TiPNRxMSk2K4ZE)
> 
> watch system work anomaly

Most likely it's a net issue

**Comment by MehmetCanWT** [comment]
> > ![Screenshot_2024-03-22-10-26-14-221_com discord](https://private-user-images.githubusercontent.com/52177084/315921584-4e5a18eb-18a8-49ff-91ed-fd8113611a1b.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwOTMxMDcsIm5iZiI6MTcxMTA5MjgwNywicGF0aCI6Ii81MjE3NzA4NC8zMTU5MjE1ODQtNGU1YTE4ZWItMThhOC00OWZmLTkxZWQtZmQ4MTEzNjExYTFiLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIyVDA3MzMyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkMTZhNmNiNzFlODM3ODU0ODJlZWNjYjgxNTk2MjcxMDBlYTNmZDhjODdhOGE5YzQ1YWVkOGFmZWI4ZjgzMzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sglcDRI_irrqGvDR8WvJlTWxDodG2TiPNRxMSk2K4ZE)
> > watch system work anomaly
> 
> Most likely it's a net issue

oh okay
