### ISSUE TITLE
webdriver失败的重试次数和时间可以增加吗？3分钟就关闭程序太短了，睡觉时网络稍不稳定就停止了。

### ISSUE THREAD

**Issue by molu000** [Yudaotor/EsportsHelper#18]
**描述 问题**
在这里清楚直白的描述问题

**如何重现**
写清楚干了什么,什么情况,如何出现的问题

**截图**
在这里附上截图

**系统版本以及软件版本**
系统:
软件:

**Comment by Yudaotor** [comment]
你这个报错看起来是因为网络问题引起的

**Comment by Yudaotor** [comment]
1.2已经加入异常提醒
