### ISSUE TITLE
可不可以加一个每隔一段时间向钉钉发送正在运行的消息，要不然出现问题闪退都不知道

### ISSUE THREAD

**Issue by yqgybtxl** [Yudaotor/EsportsHelper#19]
**描述 问题**
在这里清楚直白的描述问题

**如何重现**
写清楚干了什么,什么情况,如何出现的问题

**截图**
在这里附上截图

**系统版本以及软件版本**
系统:
软件:

**Comment by Yudaotor** [comment]
1.2已经加入异常提醒
