### ISSUE TITLE
能解决一下嘛

### ISSUE THREAD

**Issue by forever1yu** [Yudaotor/EsportsHelper#2]
Traceback (most recent call last):
  File "Twitch.py", line 19, in setTwitchQuality
  File "selenium\webdriver\remote\webelement.py", line 93, in click
  File "selenium\webdriver\remote\webelement.py", line 403, in _execute
  File "selenium\webdriver\remote\webdriver.py", line 440, in execute
  File "selenium\webdriver\remote\errorhandler.py", line 245, in check_response
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <iframe src="https://player.twitch.tv?channel=lolpacific&amp;height=100%25&amp;parent=lolesports.com&amp;referrer=https%3A%2F%2Flolesports.com%2Flive%2Fpcs%2Flolpacific&amp;theme=dark&amp;width=100%25" allowfullscreen="" scrolling="no" frameborder="0" allow="autoplay; fullscreen" title="Twitch" sandbox="allow-modals allow-scripts allow-same-origin allow-popups allow-popups-to-escape-sandbox" width="100%" height="100%" cd_frame_id_="3363368827afe4e713c19bc7564033d1"></iframe> is not clickable at point (55, 730). Other element would receive the click: <span class="osano-cm-toggle__switch osano-cm-switch"></span>
  (Session info: chrome=111.0.5563.111)
Stacktrace:
Backtrace:
        (No symbol) [0x006DDCE3]
        (No symbol) [0x006739D1]
        (No symbol) [0x00584DA8]
        (No symbol) [0x005B52EA]
        (No symbol) [0x005B3BBA]
        (No symbol) [0x005B23AD]
        (No symbol) [0x005B1027]
        (No symbol) [0x005A8D05]
        (No symbol) [0x005CAECC]
        (No symbol) [0x005A8726]
        (No symbol) [0x005CB224]
        (No symbol) [0x005DD57C]
        (No symbol) [0x005CACC6]
        (No symbol) [0x005A6F68]
        (No symbol) [0x005A80CD]
        GetHandleVerifier [0x00953832+2506274]
        GetHandleVerifier [0x00989794+2727300]
        GetHandleVerifier [0x0098E36C+2746716]
        GetHandleVerifier [0x00786690+617600]
        (No symbol) [0x0067C712]
        (No symbol) [0x00681FF8]
        (No symbol) [0x006820DB]
        (No symbol) [0x0068C63B]
        BaseThreadInitThunk [0x764C00F9+25]
        RtlGetAppContainerNamedObjectPath [0x77467BBE+286]
        RtlGetAppContainerNamedObjectPath [0x77467B8E+238]

**Comment by Yudaotor** [comment]
是网络问题吧,或者是他在操作的时候你乱动了?应该不是常态吧
