### ISSUE TITLE
[BUG]生成WebDriver失败

### ISSUE THREAD

**Issue by Notofnice** [Yudaotor/EsportsHelper#23]
**描述 问题**
我这开了VPN在chorme上直接看Esports是没问题的，但是程序无法启动，提示没有安装最新chrome，可已经是最新版的chrome了
[EsportsHelperApr-09-21-10.log](https://github.com/Yudaotor/EsportsHelper/files/11185547/EsportsHelperApr-09-21-10.log)

**如何重现**
管理员启动，无中文路径下运行都试过还是一样的问题

**截图**
![Snipaste_2023-04-09_21-14-20](https://user-images.githubusercontent.com/63146701/230774921-db51690c-d8e8-4b96-b4ce-7c2d42fba196.png)
![Snipaste_2023-04-09_21-13-01](https://user-images.githubusercontent.com/63146701/230774931-63595785-33d3-4801-b5e8-39a5ba1abc27.png)

**系统版本以及软件版本**
系统:Win10家庭版
软件:1.2.1

**Comment by Yudaotor** [comment]
这个报错原因是没有找到Chrome的可执行文件,一般这种报错会发生在没下载Chrome的时候,不过你可以试试卸载Chrome然后去官网重新安装一个
