### ISSUE TITLE
enhancement - chromium

### ISSUE THREAD

**Issue by devortath** [Yudaotor/EsportsHelper#30]
Could you make it compatible with chromium on linux? I want to use it on an ARM machine with linux and there is no Chrome for this architecture

**Comment by Yudaotor** [comment]
wdym.it can be used on linux

**Comment by xMatador-Git** [comment]
get Chromium and use this driver: `sudo apt-get install chromium-chromedriver`
works on my Ubuntu VPS and on my Pi

**Comment by devortath** [comment]
Not without Chrome, and there is not Chrome for ARM64

**Comment by Yudaotor** [comment]
![image](https://user-images.githubusercontent.com/87225219/232827280-b646728f-84dc-4ee6-827e-1c72bd24178e.png)
u mean this?

**Comment by devortath** [comment]
Yes, but thas for 64bit architecture only, there is no ARM64 version. But Chromium does. [Chromium](https://launchpad.net/ubuntu/bionic/arm64/chromium-browser)

**Comment by Yudaotor** [comment]
> Yes, but thats for 64bit architecture only, there is no ARM64 version. But Chromium does. [Chromium](https://launchpad.net/ubuntu/bionic/arm64/chromium-browser)

u can pull the newest code.maybe it can work now. I dont have ARM64 linux.so u can test yourself

**Comment by devortath** [comment]
![image](https://user-images.githubusercontent.com/94830062/233015368-bb6be895-6151-4c67-9f44-ca054f2d8e8a.png)
Still doesnt work, but ty for your efforts!

**Comment by Yudaotor** [comment]
> 

could u show me the log

**Comment by devortath** [comment]
2023-04-19 08:32:36,082 INFO: -------------------------------------------------
2023-04-19 08:32:36,083 INFO: ----------- Program started   ---------------
2023-04-19 08:32:36,083 INFO: ----------- OpenSourse in github   ---------------
2023-04-19 08:32:36,083 INFO: ----- Address: https://github.com/Yudaotor/EsportsHelper -------
2023-04-19 08:32:36,083 INFO: ----------- Please give me a star,Thanks(*^_^*) ---------------
2023-04-19 08:32:36,083 INFO: -------------------------------------------------
2023-04-19 08:32:36,185 INFO: ====== WebDriver manager ======
2023-04-19 08:32:36,190 INFO: Get LATEST chromedriver version for google-chrome None
2023-04-19 08:32:36,316 INFO: Driver [driver/.wdm/drivers/chromedriver/linux64/112.0.5615/chromedriver] found in cache
2023-04-19 08:32:36,327 ERROR: Traceback (most recent call last):
  File "/home/ubuntu/Downloads/EsportsHelper-1.4.0/main.py", line 24, in init
    driver = Webdriver(config).createWebdriver()
  File "/home/ubuntu/Downloads/EsportsHelper-1.4.0/EsportsHelper/Webdriver.py", line 32, in createWebdriver
    return uc.Chrome(options=options, driver_executable_path=driverPath, version_main=version)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/undetected_chromedriver/__init__.py", line 441, in __init__
    super(Chrome, self).__init__(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 80, in __init__
    super().__init__(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py", line 101, in __init__
    self.service.start()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/selenium/webdriver/common/service.py", line 90, in start
    self._start_process(self.path)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/selenium/webdriver/common/service.py", line 203, in _start_process
    self.process = subprocess.Popen(
  File "/usr/lib/python3.10/subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1845, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: 'driver/.wdm/drivers/chromedriver/linux64/112.0.5615/chromedriver'

**Comment by Yudaotor** [comment]
sry,no idea

**Comment by DeepDeepDeep** [comment]
> 2023-04-19 08:32:36,082 INFO: ------------------------------------------------- 2023-04-19 08:32:36,083 INFO: ----------- Program started --------------- 2023-04-19 08:32:36,083 INFO: ----------- OpenSourse in github --------------- 2023-04-19 08:32:36,083 INFO: ----- Address: https://github.com/Yudaotor/EsportsHelper ------- 2023-04-19 08:32:36,083 INFO: ----------- Please give me a star,Thanks(_^_^_) --------------- 2023-04-19 08:32:36,083 INFO: ------------------------------------------------- 2023-04-19 08:32:36,185 INFO: ====== WebDriver manager ====== 2023-04-19 08:32:36,190 INFO: Get LATEST chromedriver version for google-chrome None 2023-04-19 08:32:36,316 INFO: Driver [driver/.wdm/drivers/chromedriver/linux64/112.0.5615/chromedriver] found in cache 2023-04-19 08:32:36,327 ERROR: Traceback (most recent call last): File "/home/ubuntu/Downloads/EsportsHelper-1.4.0/main.py", line 24, in init driver = Webdriver(config).createWebdriver() File "/home/ubuntu/Downloads/EsportsHelper-1.4.0/EsportsHelper/Webdriver.py", line 32, in createWebdriver return uc.Chrome(options=options, driver_executable_path=driverPath, version_main=version) File "/home/ubuntu/.local/lib/python3.10/site-packages/undetected_chromedriver/**init**.py", line 441, in **init** super(Chrome, self).**init**( File "/home/ubuntu/.local/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 80, in **init** super().**init**( File "/home/ubuntu/.local/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py", line 101, in **init** self.service.start() File "/home/ubuntu/.local/lib/python3.10/site-packages/selenium/webdriver/common/service.py", line 90, in start self._start_process(self.path) File "/home/ubuntu/.local/lib/python3.10/site-packages/selenium/webdriver/common/service.py", line 203, in _start_process self.process = subprocess.Popen( File "/usr/lib/python3.10/subprocess.py", line 969, in **init** self._execute_child(args, executable, preexec_fn, close_fds, File "/usr/lib/python3.10/subprocess.py", line 1845, in _execute_child raise child_exception_type(errno_num, err_msg, err_filename) OSError: [Errno 8] Exec format error: 'driver/.wdm/drivers/chromedriver/linux64/112.0.5615/chromedriver'

Download chromedriver for arm from here: https://github.com/electron/electron/releases

Make sure your chrome version matches the chromedriver version.

Then make a folder and unzip the chromedriver.

Then edit the driverPath in Webdriver.py and point it to the chromedriver in that folder.

<img width="452" alt="image" src="https://user-images.githubusercontent.com/54153890/233240705-b71c8e3c-83b7-4d0f-93aa-eeb873cf4a0d.png">

**Comment by devortath** [comment]
> > 2023-04-19 08:32:36,082 INFO: ------------------------------------------------- 2023-04-19 08:32:36,083 INFO: ----------- Program started --------------- 2023-04-19 08:32:36,083 INFO: ----------- OpenSourse in github --------------- 2023-04-19 08:32:36,083 INFO: ----- Address: https://github.com/Yudaotor/EsportsHelper ------- 2023-04-19 08:32:36,083 INFO: ----------- Please give me a star,Thanks(_^_^_) --------------- 2023-04-19 08:32:36,083 INFO: ------------------------------------------------- 2023-04-19 08:32:36,185 INFO: ====== WebDriver manager ====== 2023-04-19 08:32:36,190 INFO: Get LATEST chromedriver version for google-chrome None 2023-04-19 08:32:36,316 INFO: Driver [driver/.wdm/drivers/chromedriver/linux64/112.0.5615/chromedriver] found in cache 2023-04-19 08:32:36,327 ERROR: Traceback (most recent call last): File "/home/ubuntu/Downloads/EsportsHelper-1.4.0/main.py", line 24, in init driver = Webdriver(config).createWebdriver() File "/home/ubuntu/Downloads/EsportsHelper-1.4.0/EsportsHelper/Webdriver.py", line 32, in createWebdriver return uc.Chrome(options=options, driver_executable_path=driverPath, version_main=version) File "/home/ubuntu/.local/lib/python3.10/site-packages/undetected_chromedriver/**init**.py", line 441, in **init** super(Chrome, self).**init**( File "/home/ubuntu/.local/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 80, in **init** super().**init**( File "/home/ubuntu/.local/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py", line 101, in **init** self.service.start() File "/home/ubuntu/.local/lib/python3.10/site-packages/selenium/webdriver/common/service.py", line 90, in start self._start_process(self.path) File "/home/ubuntu/.local/lib/python3.10/site-packages/selenium/webdriver/common/service.py", line 203, in _start_process self.process = subprocess.Popen( File "/usr/lib/python3.10/subprocess.py", line 969, in **init** self._execute_child(args, executable, preexec_fn, close_fds, File "/usr/lib/python3.10/subprocess.py", line 1845, in _execute_child raise child_exception_type(errno_num, err_msg, err_filename) OSError: [Errno 8] Exec format error: 'driver/.wdm/drivers/chromedriver/linux64/112.0.5615/chromedriver'
> 
> Download chromedriver for arm from here: https://github.com/electron/electron/releases
> 
> Make sure your chrome version matches the chromedriver version.
> 
> Move the "chromedriver" file here /home/USERNAME/.local/share/undetected_chromedriver/
> 
> Then edit the driverPath in Webdriver.py and point it to the chromedriver in that folder and it'll work.
> 
> ![image](https://user-images.githubusercontent.com/54153890/233248877-6b5826c0-40be-46ce-ba92-340aad1b8d85.png)

Yay, this works! But with this method it doenst use the patched undetected driver anymore, right? Or it still gets patched?

**Comment by devortath** [comment]
Great!, now that we know where is the problem, maybe Yudaotor can automate the solution. 😊

**Comment by DeepDeepDeep** [comment]
> Great!, now that we know where is the problem, maybe Yudaotor can automate the solution. 😊

It'll be hard to automate cause everyone will have different chrome version so I think he's just going to add it to the guide.

**Comment by Yudaotor** [comment]
> > Great!, now that we know where is the problem, maybe Yudaotor can automate the solution. 😊
> 
> It'll be hard to automate cause everyone will have different chrome version so I think he's just going to add it to the guide.

https://github.com/Yudaotor/EsportsHelper/wiki/The-Way-Using-Chromium-on-ARM64
