### ISSUE TITLE
想請問能否用android設備開啟此軟件

### ISSUE THREAD

**Issue by zsp40088** [Yudaotor/EsportsHelper#32]
想請問能否用android設備開啟此軟件
像之前poro的FarmerEvolved那樣

如果可以 想請問該如何操作

**Comment by Yudaotor** [comment]
> 想請問能否用android設備開啟此軟件
> 
> 像之前poro的FarmerEvolved那樣
> 
> 
> 
> 如果可以 想請問該如何操作

Termux是32位的，應該不行，chrome只有64位
