### ISSUE TITLE
Suggestion: generate config.yaml on first launch

### ISSUE THREAD

**Issue by st0nke** [Yudaotor/EsportsHelper#36]
After downloading .exe from releases in will launch with error if _config.yaml_ file is not present. I propose either adding a function to generate _config.yaml_ on first launch or adding _config.yaml_ file with the releases, so it can be filled before launching for the first time.

**Comment by Yudaotor** [comment]
> After downloading .exe from releases in will launch with error if _config.yaml_ file is not present. I propose either adding a function to generate _config.yaml_ on first launch or adding _config.yaml_ file with the releases, so it can be filled before launching for the first time.

its ady in realease .zip

**Comment by Yudaotor** [comment]
An html file to generate config.yaml is also a good idea, just like the poro one

**Comment by Yudaotor** [comment]
Finished
