### ISSUE TITLE
conda 命令未发现

### ISSUE THREAD

**Issue by hlhso** [Yudaotor/EsportsHelper#41]
https://github.com/Yudaotor/EsportsHelper/blob/ec09657dbcf68e309386a0691c8334b240d9b525/run_job.sh#L11
是要装conda才行吗，占用空间很大，有其他代替方案吗

**Comment by Yudaotor** [comment]
@Ruth-Seven

**Comment by AIUSR-TMP** [comment]
可以试试miniconda
