### ISSUE TITLE
请问如何取消默认的直播静音

### ISSUE THREAD

**Issue by S07453881** [Yudaotor/EsportsHelper#42]
请问如何取消默认的直播静音，直播静音放在后台经常会出现停止播放的状况，打开声音就不会出现这种情况。
如果不能的话，请问可否在后续更新中添加一个配置选项（如果代码复杂状况允许的话）

**Comment by Yudaotor** [comment]
> 请问如何取消默认的直播静音，直播静音放在后台经常会出现停止播放的状况，打开声音就不会出现这种情况。
> 
> 如果不能的话，请问可否在后续更新中添加一个配置选项（如果代码复杂状况允许的话）

没有默认直播静音，会打开声音的，听不见声音是因为浏览器被整体静音了

**Comment by S07453881** [comment]
浏览器没有整体静音，运行程序时看到程序在打开直播时浏览器是有声音的，但会在设置直播清晰度的同时点击声音图标将直播静音

**Comment by Yudaotor** [comment]
> 浏览器没有整体静音，运行程序时看到程序在打开直播时浏览器是有声音的，但会在设置直播清晰度的同时点击声音图标将直播静音

啊？不会啊，你用的什么版本

**Comment by S07453881** [comment]
> > 浏览器没有整体静音，运行程序时看到程序在打开直播时浏览器是有声音的，但会在设置直播清晰度的同时点击声音图标将直播静音
> 
> 啊？不会啊，你用的什么版本

最新的那个板本

**Comment by Yudaotor** [comment]
> > > 浏览器没有整体静音，运行程序时看到程序在打开直播时浏览器是有声音的，但会在设置直播清晰度的同时点击声音图标将直播静音
> > 
> > 
> > 啊？不会啊，你用的什么版本
> 
> 最新的那个板本

看了下,浏览器确实是不会发出声音的,至于你说的静音的问题,这个一般来说都是会打开声音的.不过在下版本中会增加一个判断,来处理一些特殊情况.

**Comment by S07453881** [comment]
> > > > 浏览器没有整体静音，运行程序时看到程序在打开直播时浏览器是有声音的，但会在设置直播清晰度的同时点击声音图标将直播静音
> > > 
> > > 
> > > 啊？不会啊，你用的什么版本
> > 
> > 
> > 最新的那个板本
> 
> 看了下,浏览器确实是不会发出声音的,至于你说的静音的问题,这个一般来说都是会打开声音的.不过在下版本中会增加一个判断,来处理一些特殊情况.

好的，感谢大大的辛勤付出

**Comment by Yuanlailai** [comment]
> > > > 浏览器没有整体静音，运行程序时看到程序在打开直播时浏览器是有声音的，但会在设置直播清晰度的同时点击声音图标将直播静音
> > > 
> > > 
> > > 啊？不会啊，你用的什么版本
> > 
> > 
> > 最新的那个板本
> 
> 看了下,浏览器确实是不会发出声音的,至于你说的静音的问题,这个一般来说都是会打开声音的.不过在下版本中会增加一个判断,来处理一些特殊情况.

这个问题（切换标签页会自动暂停直播）的根源是，网站权限需要将“声音（自动）”改为“声音（允许）”
