### ISSUE TITLE
TFT的比赛貌似不识别

### ISSUE THREAD

**Issue by S07453881** [Yudaotor/EsportsHelper#44]
可能是因为他的标题是预告？

**Comment by Yudaotor** [comment]
是，所以需要在配置里关闭ignoreBroadCast

**Comment by Yudaotor** [comment]
> `ignoreBroadCast: False` 了，还是没有检测到当前的TFT比赛直播

不会的,重开看看

**Comment by Yudaotor** [comment]
> > > `ignoreBroadCast: False` 了，还是没有检测到当前的TFT比赛直播
> > 
> > 
> > 不会的,重开看看
> 
> 试过了，还是不行
> 
> ```
> 2023-05-27 16:18:16,716 INFO: -----------------------------------------------------------------------
> 2023-05-27 16:18:16,716 INFO: ---------------------- Program started 1.6.2   -----------------------
> 2023-05-27 16:18:16,716 INFO: ---------------------- Open Source on github  ----------------------
> 2023-05-27 16:18:16,716 INFO: ------- Address: https://github.com/Yudaotor/EsportsHelper ------
> 2023-05-27 16:18:16,716 INFO: ---------------- Please give me a star,Thanks(*^_^*)  ---------------
> 2023-05-27 16:18:16,716 INFO: -----------------------------------------------------------------------
> 2023-05-27 16:18:17,423 INFO: 获取参数文件成功
> 2023-05-27 16:18:18,129 INFO: ====== WebDriver manager ======
> 2023-05-27 16:18:18,129 INFO: ====== WebDriver manager ======
> 2023-05-27 16:18:18,129 INFO: 正在准备中...
> 2023-05-27 16:18:18,298 INFO: Get LATEST chromedriver version for google-chrome 113.0.5672
> 2023-05-27 16:18:18,590 INFO: About to download new driver from https://chromedriver.storage.googleapis.com/113.0.5672.63/chromedriver_linux64.zip
> 2023-05-27 16:18:19,400 INFO: Driver has been saved in cache [driver/.wdm/drivers/chromedriver/linux64/113.0.5672]
> 2023-05-27 16:18:19,407 INFO: patching driver executable driver/.wdm/drivers/chromedriver/linux64/113.0.5672/chromedriver
> 2023-05-27 16:18:20,309 INFO: setting properties for headless
> 2023-05-27 16:18:23,097 INFO: 切换网页语言成功
> 2023-05-27 16:18:30,513 INFO: 登录中...
> 2023-05-27 16:18:35,727 INFO: 账密 提交成功
> 2023-05-27 16:18:41,023 INFO: 好嘞 登录成功
> 2023-05-27 16:18:43,130 INFO: 初始化掉落数
> 2023-05-27 16:18:47,578 INFO: 开始检查...
> 2023-05-27 16:18:47,601 INFO: 检查赛区直播状态...
> 2023-05-27 16:18:50,260 INFO: 检查掉落数...
> 2023-05-27 16:18:51,965 INFO: 本次运行掉落总和:0 | 生涯总掉落:101 | 总观看时长: 688
> 2023-05-27 16:18:57,663 INFO: 没有赛区正在直播
> 2023-05-27 16:19:00,765 INFO: 下次检查在: 05-27 16:29:10
> 2023-05-27 16:19:00,765 INFO: ==================================================
> 2023-05-27 16:29:11,824 INFO: 开始检查...
> 2023-05-27 16:29:11,831 INFO: 检查赛区直播状态...
> 2023-05-27 16:29:15,175 INFO: 进入休眠时间
> 2023-05-27 16:29:20,344 INFO: 所有窗口已关闭
> 2023-05-27 16:29:20,347 INFO: 预计休眠状态将持续到 20 点
> 2023-05-27 16:29:20,350 INFO: 下次检查在: 05-27 17:29:19
> 2023-05-27 16:29:20,352 INFO: ==================================================
> 2023-05-27 17:29:20,355 INFO: 开始检查...
> 2023-05-27 17:29:20,377 INFO: 处于休眠时间...
> 2023-05-27 17:29:20,377 INFO: 预计休眠状态将持续到 20 点
> 2023-05-27 17:29:20,378 INFO: 下次检查在: 05-27 18:29:19
> 2023-05-27 17:29:20,379 INFO: ==================================================
> 2023-05-27 18:29:20,476 INFO: 开始检查...
> 2023-05-27 18:29:20,513 INFO: 处于休眠时间...
> 2023-05-27 18:29:20,513 INFO: 预计休眠状态将持续到 20 点
> 2023-05-27 18:29:20,514 INFO: 下次检查在: 05-27 19:29:19
> 2023-05-27 18:29:20,515 INFO: ==================================================
> 2023-05-27 19:29:20,621 INFO: 开始检查...
> 2023-05-27 19:29:20,659 INFO: 休眠时间结束
> 2023-05-27 19:29:22,098 INFO: 检查掉落数...
> 2023-05-27 19:29:26,607 INFO: 本次运行掉落总和:0 | 生涯总掉落:101 | 总观看时长: 688
> 2023-05-27 19:29:32,120 INFO: 没有赛区正在直播
> 2023-05-27 19:29:35,215 INFO: 下次检查在: 05-27 19:42:05
> 2023-05-27 19:29:35,216 INFO: ==================================================
> 2023-05-27 19:42:06,318 INFO: 开始检查...
> 2023-05-27 19:42:06,321 INFO: 检查赛区直播状态...
> 2023-05-27 19:42:09,654 INFO: 检查掉落数...
> 2023-05-27 19:42:12,544 INFO: 本次运行掉落总和:0 | 生涯总掉落:101 | 总观看时长: 688
> 2023-05-27 19:42:18,460 INFO: 没有赛区正在直播
> 2023-05-27 19:42:21,558 INFO: 下次检查在: 05-27 19:55:21
> 2023-05-27 19:42:21,558 INFO: ==================================================
> 2023-05-27 19:55:22,660 INFO: 开始检查...
> 2023-05-27 19:55:22,662 INFO: 检查赛区直播状态...
> 2023-05-27 19:55:26,640 INFO: 检查掉落数...
> 2023-05-27 19:55:29,981 INFO: 本次运行掉落总和:0 | 生涯总掉落:101 | 总观看时长: 688
> 2023-05-27 19:55:35,872 INFO: 没有赛区正在直播
> 2023-05-27 19:55:38,970 INFO: 下次检查在: 05-27 20:07:48
> 2023-05-27 19:55:38,970 INFO: ==================================================
> 2023-05-27 20:07:50,072 INFO: 开始检查...
> 2023-05-27 20:07:50,076 INFO: 检查赛区直播状态...
> 2023-05-27 20:07:52,888 INFO: 检查掉落数...
> 2023-05-27 20:07:56,273 INFO: 本次运行掉落总和:0 | 生涯总掉落:101 | 总观看时长: 688
> 2023-05-27 20:08:02,478 INFO: 没有赛区正在直播
> 2023-05-27 20:08:05,574 INFO: 下次检查在: 05-27 20:17:25
> 2023-05-27 20:08:05,574 INFO: ==================================================
> 2023-05-27 20:17:26,674 INFO: 开始检查...
> 2023-05-27 20:17:26,685 INFO: 检查赛区直播状态...
> 2023-05-27 20:17:29,690 INFO: 检查掉落数...
> 2023-05-27 20:17:32,627 INFO: 本次运行掉落总和:0 | 生涯总掉落:101 | 总观看时长: 688
> 2023-05-27 20:17:38,395 INFO: 没有赛区正在直播
> 2023-05-27 20:17:41,491 INFO: 下次检查在: 05-27 20:29:41
> 2023-05-27 20:17:41,491 INFO: ==================================================
> 2023-05-27 20:29:42,534 INFO: 开始检查...
> 2023-05-27 20:29:42,544 INFO: 检查赛区直播状态...
> 2023-05-27 20:29:46,086 INFO: 检查掉落数...
> 2023-05-27 20:29:50,674 INFO: 本次运行掉落总和:0 | 生涯总掉落:101 | 总观看时长: 688
> 2023-05-27 20:29:57,327 INFO: 没有赛区正在直播
> 2023-05-27 20:30:00,731 INFO: 下次检查在: 05-27 20:38:10
> 2023-05-27 20:30:00,731 INFO: ==================================================
> 2023-05-27 20:38:11,832 INFO: 开始检查...
> 2023-05-27 20:38:11,843 INFO: 检查赛区直播状态...
> 2023-05-27 20:38:15,090 INFO: 检查掉落数...
> 2023-05-27 20:38:18,924 INFO: 本次运行掉落总和:0 | 生涯总掉落:101 | 总观看时长: 688
> 2023-05-27 20:38:25,059 INFO: 没有赛区正在直播
> 2023-05-27 20:38:28,161 INFO: 下次检查在: 05-27 20:48:28
> 2023-05-27 20:38:28,161 INFO: ==================================================
> 2023-05-27 20:48:29,244 INFO: 开始检查...
> 2023-05-27 20:48:29,247 INFO: 检查赛区直播状态...
> 2023-05-27 20:48:32,175 INFO: 检查掉落数...
> 2023-05-27 20:48:36,067 INFO: 本次运行掉落总和:0 | 生涯总掉落:101 | 总观看时长: 688
> 2023-05-27 20:48:41,762 INFO: 没有赛区正在直播
> 2023-05-27 20:48:44,865 INFO: 下次检查在: 05-27 21:00:24
> 2023-05-27 20:48:44,866 INFO: ==================================================
> 2023-05-27 21:00:25,969 INFO: 开始检查...
> 2023-05-27 21:00:25,979 INFO: 检查赛区直播状态...
> 2023-05-27 21:00:29,955 INFO: 检查掉落数...
> 2023-05-27 21:00:34,573 INFO: 本次运行掉落总和:0 | 生涯总掉落:101 | 总观看时长: 688
> 2023-05-27 21:00:41,376 INFO: 没有赛区正在直播
> 2023-05-27 21:00:44,757 INFO: 下次检查在: 05-27 21:13:04
> 2023-05-27 21:00:44,757 INFO: ==================================================
> 2023-05-27 21:13:05,860 INFO: 开始检查...
> 2023-05-27 21:13:05,863 INFO: 检查赛区直播状态...
> 2023-05-27 21:13:09,648 INFO: 检查掉落数...
> 2023-05-27 21:13:14,581 INFO: 本次运行掉落总和:0 | 生涯总掉落:101 | 总观看时长: 688
> 2023-05-27 21:13:20,692 INFO: 没有赛区正在直播
> 2023-05-27 21:13:24,556 INFO: 下次检查在: 05-27 21:23:04
> 2023-05-27 21:13:24,556 INFO: ==================================================
> 2023-05-27 21:23:05,666 INFO: 开始检查...
> 2023-05-27 21:23:05,676 INFO: 检查赛区直播状态...
> 2023-05-27 21:23:09,334 INFO: 检查掉落数...
> 2023-05-27 21:23:14,591 INFO: 本次运行掉落总和:0 | 生涯总掉落:101 | 总观看时长: 688
> 2023-05-27 21:23:20,788 INFO: 没有赛区正在直播
> 2023-05-27 21:23:24,605 INFO: 下次检查在: 05-27 21:34:44
> 2023-05-27 21:23:24,606 INFO: ==================================================
> 2023-05-27 21:34:45,658 INFO: 开始检查...
> 2023-05-27 21:34:45,661 INFO: 检查赛区直播状态...
> 2023-05-27 21:34:48,883 INFO: 检查掉落数...
> 2023-05-27 21:34:54,761 INFO: 本次运行掉落总和:0 | 生涯总掉落:101 | 总观看时长: 688
> 2023-05-27 21:35:01,380 INFO: 没有赛区正在直播
> 2023-05-27 21:35:04,855 INFO: 下次检查在: 05-27 21:47:44
> 2023-05-27 21:35:04,855 INFO: ==================================================
> ```

是不是你配置输入错了,没有遇到说检测不到的反馈过.我自己也是一直都没有问题的.你重新搞个文件夹重新配置一下试试

**Comment by Yudaotor** [comment]
确实是配置错了,你发现没有,你单词拼错了.
