### ISSUE TITLE
无法找到Google chrome

### ISSUE THREAD

**Issue by QianQQQ** [Yudaotor/EsportsHelper#48]
系统 Debian10

运行报错
WebDriver generation failure!
The latest version of Google Chrome is not found.
Please check if Chrome downloaded or has the latest version.
Or try opening it as an administrator.
If it still doesn't work, try reinstalling Google Chrome.

但我使用google-chrome --version 会输出Google Chrome 114.0.5735.106，应该是成功安装的

**Comment by Yudaotor** [comment]
我把requirements回退了,你现在重新pull一下再试试.前几天有人反馈过新版本的环境有问题

**Comment by QianQQQ** [comment]
感谢！
