### ISSUE TITLE
can I add a second account? 我能添加第二個賬號嗎？

### ISSUE THREAD

**Issue by noobyweeby** [Yudaotor/EsportsHelper#50]
我現在複製了整個文件夾來挂另一個賬號，好奇能否直接在config裏添加更多賬號？
Currently I copied the entire folder for the second account, wondering if I can add another account directly in the config file?

**Comment by Yudaotor** [comment]
> 

no

**Comment by DRCX** [comment]
1个文件夹内的一个配置文件对应1个账户
