### ISSUE TITLE
警告：停止获取Drop

### ISSUE THREAD

**Issue by chase-forever** [Yudaotor/EsportsHelper#52]
大佬，我设置了企业微信推送，给我推送了这个，这是什么情况？还有这个挂着能连续运行几天呢？感觉时间一长命令窗口就会自己关闭

**Comment by Yudaotor** [comment]
警告说明网络不良导致的或者是脚本哪里出问题了,提醒你去查看避免不知情下停止挂了.连续的话理论没有设限,看你网络情况怎么样,自己关闭绝大多数原因也是网络问题
