### ISSUE TITLE
Bot not working with latest Chrome version

### ISSUE THREAD

**Issue by EmbitionReaper** [Yudaotor/EsportsHelper#55]
Currently running Version 115.0.5790.99 of chrome and getting this message when attempting to start 

WebDriver generation failure!
Is Google Chrome installed?
Is there a network problem? Check VPN availability if one connected
If it still doesn't work, try reinstalling Google Chrome.
Press Enter to exit.

Was working fine before the update

**Comment by Yudaotor** [comment]
webdriver not match 115 now.downgrade to 114 will fix this issue

**Comment by Yuanlailai** [comment]
> webdriver not match 115 now.downgrade to 114 will fix this issue

看这篇文章，大概意思是115以上的版本不会发布在chrome driver上了？
After reading this article, it probably means that the version above 115 will not be released on the chrome driver?

https://chromedriver.chromium.org/downloads/version-selection

**Comment by Yudaotor** [comment]
> > webdriver not match 115 now.downgrade to 114 will fix this issue
> 
> 看这篇文章，大概意思是115以上的版本不会发布在chrome driver上了？ After reading this article, it probably means that the version above 115 will not be released on the chrome driver?
> 
> https://chromedriver.chromium.org/downloads/version-selection

等undetected-chromedriver库更新吧 等他修复这个问题应该就没事了

**Comment by maskX1** [comment]
Uninstall your chorme retain data
install old version

114.0.5735.199_x64
https://mega.nz/file/4G5FFBhI#bPZNi3SGV0E_ZSf5s1Tr7zc8CQbuBepw1oabDpPY6t8

**Comment by Yudaotor** [comment]
2.1.2 fix it.
