### ISSUE TITLE
登录异常/The login is abnormal

### ISSUE THREAD

**Issue by OvOhallo123** [Yudaotor/EsportsHelper#57]
自动输入账号密码后，卡在登录页面，然后闪退
After automatically entering username/password, the website doesn't respond and unexpected quit happens

**Comment by Yudaotor** [comment]
最好使用配置 headless: False来观察出现了什么错误导致的.

**Comment by OvOhallo123** [comment]
> 最好使用配置 headless: False来观察出现了什么错误导致的.

今天又可以正常使用了，可能是浏览器的问题吧
