### ISSUE TITLE
浏览器自动升到15，登录不了，卸载重安2次登录还是没用

### ISSUE THREAD

**Issue by keepmi** [Yudaotor/EsportsHelper#58]
谷歌浏览器自动更新了115，登录就变成一串红字。然后重新安装了两次114还是一串红字登录不了

**Comment by redr00t** [comment]
Requirements.txt

plyer==2.1.0
PyYAML==6.0
requests==2.27.0
retrying==1.3.4
rich==13.3.4
selenium==4.10.0
undetected_chromedriver==3.5.0
urllib3==1.26.15
webdriver_manager==3.8.5
cloudscraper==1.2.71

**Comment by maskX1** [comment]
卸载你的google chrome 然后保留数据
https://mega.nz/file/4G5FFBhI#bPZNi3SGV0E_ZSf5s1Tr7zc8CQbuBepw1oabDpPY6t8
安装旧版本

**Comment by Yudaotor** [comment]
> 谷歌浏览器自动更新了115，登录就变成一串红字。然后重新安装了两次114还是一串红字登录不了

退回到114就可以

**Comment by keepmi** [comment]
> 卸载你的google chrome 然后保留数据 https://mega.nz/file/4G5FFBhI#bPZNi3SGV0E_ZSf5s1Tr7zc8CQbuBepw1oabDpPY6t8 这个是114版本google下载 安装旧版本

谢了，这个版本才是对的

**Comment by keepmi** [comment]
> Requirements.txt
> 
> plyer==2.1.0 PyYAML==6.0 requests==2.27.0 retrying==1.3.4 rich==13.3.4 selenium==4.10.0 undetected_chromedriver==3.5.0 urllib3==1.26.15 webdriver_manager==3.8.5 cloudscraper==1.2.71

保存了，谢了

**Comment by keepmi** [comment]
> > 谷歌浏览器自动更新了115，登录就变成一串红字。然后重新安装了两次114还是一串红字登录不了
> 
> 退回到114就可以

先下载的114有问题，楼上的可以用了
