### ISSUE TITLE
fix and download:not working latest Chrome version,解决google chorme问题看这里

### ISSUE THREAD

**Issue by maskX1** [Yudaotor/EsportsHelper#59]
Uninstall your chorme retain data
install old version

卸载你的chorme保留数据
安装旧版本

114.0.5735.199_x64
https://mega.nz/file/4G5FFBhI#bPZNi3SGV0E_ZSf5s1Tr7zc8CQbuBepw1oabDpPY6t8

if google auto update.watch here
enlish::
https://www.makeuseof.com/tag/stop-automatic-chrome-updates-windows/
中文:
https://www.cnblogs.com/mq0036/p/13947021.html

**Comment by eastcarrot** [comment]
什么时候更新2.1.2呢

**Comment by Yudaotor** [comment]
> 什么时候更新2.1.2呢

快了

**Comment by eastcarrot** [comment]
哥，加油！

**Comment by Yudaotor** [comment]
2.1.2 fix
