### ISSUE TITLE
有头模式下，误操作导致页面被关闭，就会导致程序崩溃，建议添加catch

### ISSUE THREAD

**Issue by Ruth-Seven** [Yudaotor/EsportsHelper#6]
from selenium.common.exceptions import NoSuchWindowException
            except NoSuchWindowException as e:

**Comment by Yudaotor** [comment]
没有这个必要吧,页面都被关闭了,程序留着有什么用呢.直接重开就好了

**Comment by Ruth-Seven** [comment]
程序崩溃的表现是 这个一直卡在循环里 你catch了所有exception 结果输出了非常多的无效错误log

**Comment by Yudaotor** [comment]
> 程序崩溃的表现是 这个一直卡在循环里 你catch了所有exception 结果输出了非常多的无效错误log

懂你意思了

**Comment by Ruth-Seven** [comment]
而且还有其他错误

最好还是设置一下catch最大次数
