### ISSUE TITLE
Minimize to tray

### ISSUE THREAD

**Issue by NaniDaFuck** [Yudaotor/EsportsHelper#62]
is there a way to minimize program to tray so it doesn't pop up

**Comment by Yudaotor** [comment]
sry idk

**Comment by Yuanlailai** [comment]
Maybe u want the headless mode

**Comment by NaniDaFuck** [comment]
Yes it would be useful

**Comment by NaniDaFuck** [comment]
> Maybe u want the headless mode

thank you i just found it in config <3
