### ISSUE TITLE
自动休眠问题

### ISSUE THREAD

**Issue by chase-forever** [Yudaotor/EsportsHelper#63]
大神你好，我设置了自动休眠，但是我看下场比赛到8.1（明天）的17：00了，现在是7.31的11点，它并没有切换到休眠状态，这是为啥？

**Comment by chase-forever** [comment]
我看现在（13：00）它是在线状态，直播赛区显示是LCK_CL，直播信息是空的（0/3），然后安全模式是开着的，下场比赛依旧显示的是8.1号17：00的LPL比赛，检测时间仍然按照600s也就是每隔10分钟进行更新。

**Comment by Yudaotor** [comment]
> 我看现在（13：00）它是在线状态，直播赛区显示是LCK_CL，直播信息是空的（0/3），然后安全模式是开着的，下场比赛依旧显示的是8.1号17：00的LPL比赛，检测时间仍然按照600s也就是每隔10分钟进行更新。

睡眠逻辑遇到31号和1号对比的地方有点问题 明天应该就会恢复正常的睡眠了

**Comment by chase-forever** [comment]
还有刚18：00多又多次出现“获取reward网站失败，正在重试”，然后又出现“统计掉落数出错,掉落数小于0”的红字，接着是“LCK_CHALLENGERS_LEAGUE 比赛跳过”的日志，再接着又是一连串的“获取reward网站失败，正在重试”和接下来的“统计掉落数出错,掉落数小于0”的红字，到现在是快17：00还是这样。

**Comment by chase-forever** [comment]
还有刚18：00多又多次出现“获取reward网站失败，正在重试”，然后又出现“统计掉落数出错,掉落数小于0”的红字，接着是“LCK_CHALLENGERS_LEAGUE 比赛跳过”的日志，再接着又是一连串的“获取reward网站失败，正在重试”和接下来的“统计掉落数出错,掉落数小于0”的红字，到现在是快19：00还是这样。

**Comment by Yudaotor** [comment]
> 还有刚18：00多又多次出现“获取reward网站失败，正在重试”，然后又出现“统计掉落数出错,掉落数小于0”的红字，接着是“LCK_CHALLENGERS_LEAGUE 比赛跳过”的日志，再接着又是一连串的“获取reward网站失败，正在重试”和接下来的“统计掉落数出错,掉落数小于0”的红字，到现在是快19：00还是这样。

这就是你网络问题了

**Comment by chase-forever** [comment]
不是吧，我18：00多那会儿特意打开了观赛的网址，比赛正常能看，奖励那也能正常显示，现在（20：00）又打开了一次，也是比赛和奖励那都正常能看，但是我看脚本那还是显示总掉落为负值，获取reward网站失败的状态。
