### ISSUE TITLE
Farmer not working when on VPS

### ISSUE THREAD

**Issue by EmbitionReaper** [Yudaotor/EsportsHelper#68]
Using a VPS to farm drops but the program always fails. Is there a fix for this?

![Screenshot (130)](https://github.com/Yudaotor/EsportsHelper/assets/139997792/65690339-86f6-4743-90a5-e3334edebbdc)

**Comment by Yudaotor** [comment]
Nvm.lcs is offline but riot didn’t change its status

**Comment by EmbitionReaper** [comment]
The same happened with the other regions as well. No drops while it was active. 

![Screenshot (131)](https://github.com/Yudaotor/EsportsHelper/assets/139997792/92f27d0f-fab3-480f-98b7-0705e07d79c3)

**Comment by Yudaotor** [comment]
> The same happened with the other regions as well. No drops while it was active.
> 
> ![Screenshot (131)](https://user-images.githubusercontent.com/139997792/258711855-92f27d0f-fab3-480f-98b7-0705e07d79c3.png)

show me the log file. it looks like net issue

**Comment by EmbitionReaper** [comment]
[EsportsHelperV2.2.0_08.06_01-17.log](https://github.com/Yudaotor/EsportsHelper/files/12286792/EsportsHelperV2.2.0_08.06_01-17.log)

**Comment by Yudaotor** [comment]
> [EsportsHelperV2.2.0_08.06_01-17.log](https://github.com/Yudaotor/EsportsHelper/files/12286792/EsportsHelperV2.2.0_08.06_01-17.log)

net issue probably

**Comment by EmbitionReaper** [comment]
How would I fix net issue?

**Comment by Yudaotor** [comment]
> How would I fix net issue?



> How would I fix net issue?

are u use headless mode?if not? try headless

**Comment by EmbitionReaper** [comment]
Headless mode fixed the problem

**Comment by Yuanlailai** [comment]
your vps doesnt have a mouse, so if u dont use headless mode, the website will be a blank page. (when I use remote desktop to move my mouse, the website will be normal.)
