### ISSUE TITLE
生成webdriver失败

### ISSUE THREAD

**Issue by chase-forever** [Yudaotor/EsportsHelper#69]
刚下了最新版本2.2.0，一直报这个错，想知道最新版本的驱动还是114.0.5735吗，上次已经下了这个版本并设置了不会更新，网络线路检查也没有问题，想知道是什么原因？

**Comment by Yudaotor** [comment]
> 刚下了最新版本2.2.0，一直报这个错，想知道最新版本的驱动还是114.0.5735吗，上次已经下了这个版本并设置了不会更新，网络线路检查也没有问题，想知道是什么原因？

2.1.2就已经修复了115版本以上不能用的问题 所以现在都是要最新版谷歌浏览器的
