### ISSUE TITLE
希望新增自訂瀏覽器路徑功能

### ISSUE THREAD

**Issue by zhtw2013** [Yudaotor/EsportsHelper#7]
希望能新增自訂瀏覽器路徑的功能
電腦沒有安裝 Chrome

想用 Portable 的 Cent Browser 或 Firefox 來執行這個程式

感謝！

**Comment by Yudaotor** [comment]
脚本用的是undetected_chromedriver爲了減少些被riot檢測的風險(雖説也不知道有沒用),而這個第三方庫只支持chrome.雖説可以直接用selenium本來就有的庫可以實現firefox這些支持,但是我個人覺得不是很妥所以就沒有這麽寫.畢竟安裝一個Chrome也不難是吧

**Comment by zhtw2013** [comment]
不安裝 Chrome 是不想裝啊...
自訂路徑是能方便第三方 Chromium 核心使用
像說我的 Cent 就是第三方 Chromium
我是打算弄一個  Portable 版瀏覽器專門用來執行這個程式

不過不支援也沒辦法
我再想辦法吧
感謝作者回覆！

**Comment by Yudaotor** [comment]
> 

其實我不是很懂使用Portable式軟體的初衷是什麽,難道是存儲不夠嗎 還是說單純不想裝Chrome ㄏㄏ

**Comment by zhtw2013** [comment]
> > 
> 
> 其實我不是很懂使用Portable式軟體的初衷是什麽,難道是存儲不夠嗎 還是說單純不想裝Chrome ㄏㄏ

1.不想裝 Chrome。系統內建的 Edge 完全能取代 Chrome 了
    裝個 Chorme 背景還有程式偷偷常駐，搞強制更新
    電腦內強制更新的流氓瀏覽器有 Edge 一個就夠了

2.用 Protable 是為了方便管理，每個 Portable  Profile 分作不同用途使用
    
    大概4這樣。

**Comment by Shadowgraphs** [comment]
> 1.不想裝 Chrome。系統內建的 Edge 完全能取代 Chrome 了 裝個 Chorme 背景還有程式偷偷常駐，搞強制更新 電腦內強制更新的流氓瀏覽器有 Edge 一個就夠了

undetected_chromedriver虽然说是支持Chromium based浏览器，但我试了下，设置了edge浏览器位置和驱动位置，无法运行。
undetected-chromedriver issues: [Could you provide an example, on how to run it with Edge?](https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/70)
最后还是乖乖下了chrome

**Comment by Yudaotor** [comment]
將在下個版本中支持自訂瀏覽器路徑(意味著可以使用Chrome Protable)
