### ISSUE TITLE
观看异常

### ISSUE THREAD

**Issue by EmpCCC** [Yudaotor/EsportsHelper#74]
[EsportsHelperV2.2.0_08.11_19-01.log](https://github.com/Yudaotor/EsportsHelper/files/12321391/EsportsHelperV2.2.0_08.11_19-01.log)
![QQ截图20230811201517](https://github.com/Yudaotor/EsportsHelper/assets/68339311/9ba2fefb-d355-4cf1-bddf-757fe13a5f06)

**Comment by EmpCCC** [comment]
奇妙的好了

**Comment by Yudaotor** [comment]
网络不稳定
