### ISSUE TITLE
[feature request] 希望增加胶囊掉落&状态异常通知

### ISSUE THREAD

**Issue by zzz6839** [Yudaotor/EsportsHelper#8]
希望如poro和你其他项目那样，增加discord,telegram,dingding,bark有关胶囊掉落，账号异常状态的通知。

**Comment by Yudaotor** [comment]
> 希望如poro和你其他项目那样，增加discord,telegram,dingding,bark有关胶囊掉落，账号异常状态的通知。

掉落提醒已经写好了,将在下个版本中支持

**Comment by Yudaotor** [comment]
Debug的话，log里应该是有的吧

**Comment by Yudaotor** [comment]
> > Debug的话，log里应该是有的吧
> 
> 
> 
> 有的，那希望能有状态异常退出的推送，或者逐步增加重试的间隔时间，让脚本能一直运行下去。
> 
> 
> 
> ```
> 
> 2023-03-30 07:35:43,791 INFO: 下一次检查在: 2023-03-30 07:46:33.791344
> 
> 2023-03-30 07:46:33,892 INFO: ●_● 开始检查直播...
> 
> 2023-03-30 07:56:46,993 ERROR: Q_Q webdriver发生错误, 重试中
> 
> 2023-03-30 07:56:49,004 INFO: ●_● 开始检查直播...
> 
> 2023-03-30 08:07:02,093 ERROR: Q_Q webdriver发生错误, 重试中
> 
> 2023-03-30 08:07:04,096 INFO: ●_● 开始检查直播...
> 
> 2023-03-30 08:17:17,177 ERROR: Q_Q webdriver发生错误, 重试中
> 
> 2023-03-30 08:17:19,181 ERROR: Q_Q webdriver发生错误, 将于3秒后退出...
> 
> 2023-03-30 08:21:58,054 INFO: -------------------------------------------------
> 
> ```

你是在linux上运行还是win

**Comment by Yudaotor** [comment]
Linux的话是需要在配置里加一句的

**Comment by Yudaotor** [comment]
下版本修复
