### ISSUE TITLE
UserDataDir issue

### ISSUE THREAD

**Issue by NaniDaFuck** [Yudaotor/EsportsHelper#82]
when i try to set UserDataDir i get this error 
![image](https://github.com/Yudaotor/EsportsHelper/assets/70827970/dc610cd9-dd85-49c5-8fa1-712dbf2e6e04)

![image](https://github.com/Yudaotor/EsportsHelper/assets/70827970/c5e86c80-7df0-4094-a8be-444091c697d7)

i tried to change language but it doesn't work either.

**Comment by Yudaotor** [comment]
It means ur config.yaml file format is incorrect.u can use config-helper to generate

**Comment by NaniDaFuck** [comment]
can u send me screenhot for UserDataDir u using cause i tried everything it always gives me this error 
![image](https://github.com/Yudaotor/EsportsHelper/assets/70827970/9cdfb90a-8f19-4a06-9c47-51f01a45495e)

**Comment by NaniDaFuck** [comment]
i tried config maker and tried other configs in github page nothing works gives me same error everytime for some reason

**Comment by NaniDaFuck** [comment]
i got it work somehow ...
