### ISSUE TITLE
Youtube Auto-Switch

### ISSUE THREAD

**Issue by HakkaYoro** [Yudaotor/EsportsHelper#89]
I'm on Fedora 38, the program fails to automatically switch stream from Twitch to Youtube, here's the log
[EsportsHelperV2.3.1_10.09_00-04.log](https://github.com/Yudaotor/EsportsHelper/files/12842623/EsportsHelperV2.3.1_10.09_00-04.log)
(I had to turn headless to False for manually switching the stream and it worked perfectly after that)

**Comment by Yudaotor** [comment]
reopen it.i add wqs now

**Comment by HakkaYoro** [comment]
I forgot to answer, it worked, thanks
