### ISSUE TITLE
headless为False，网页打开为空白页

### ISSUE THREAD

**Issue by Zhoudamaoa** [Yudaotor/EsportsHelper#93]

**Comment by Zhoudamaoa** [comment]
![blank](https://github.com/Yudaotor/EsportsHelper/assets/148020295/22983c76-938a-4b9b-bb63-977bb63a1595)

**Comment by Yudaotor** [comment]
空白页是因为现在没比赛,进入了休眠模式啦

**Comment by Zhoudamaoa** [comment]
> 空白页是因为现在没比赛,进入了休眠模式啦
好嘞，谢谢
